Farma24/Controllers/EncomendasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Farma24.Models;

namespace Farma24.Controllers
{
    public class EncomendasController : Controller
    {
        private Farma24DBEntities db = new Farma24DBEntities();

        // GET: Encomendas
        public ActionResult Index()
        {

            var mail= User.Identity.Name;
            var user = db.Utilizadors.Find(mail);
            var encomendas = db.Encomendas.Include(e => e.Fatura).Include(e => e.Morada1).Include(e => e.Utilizador).Where(e => e.Utilizador.email.Equals(mail));
            return View(encomendas.ToList());
        }

        // GET: Encomendas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(id);
            if (encomenda == null)
            {
                return HttpNotFound();
            }
            return View(encomenda);
        }

        // GET: Encomendas/Create
        public ActionResult Create()
        {
            ViewBag.Fatura_referencia = new SelectList(db.Faturas, "referencia", "metodoPagamento");
            ViewBag.morada = new SelectList(db.Moradas, "id", "cidade");
            ViewBag.email = new SelectList(db.Utilizadors, "email", "password");
            return View();
        }

        // POST: Encomendas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,estado,email,morada,inicio,fim,custoTotal,detalhes,Fatura_referencia")] Encomenda encomenda)
        {
            if (ModelState.IsValid)
            {
                db.Encomendas.Add(encomenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Fatura_referencia = new SelectList(db.Faturas, "referencia", "metodoPagamento", encomenda.Fatura_referencia);
            ViewBag.morada = new SelectList(db.Moradas, "id", "cidade", encomenda.morada);
            ViewBag.email = new SelectList(db.Utilizadors, "email", "password", encomenda.email);
            return View(encomenda);
        }

        // GET: Encomendas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(id);
            if (encomenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.Fatura_referencia = new SelectList(db.Faturas, "referencia", "metodoPagamento", encomenda.Fatura_referencia);
            ViewBag.morada = new SelectList(db.Moradas, "id", "cidade", encomenda.morada);
            ViewBag.email = new SelectList(db.Utilizadors, "email", "password", encomenda.email);
            return View(encomenda);
        }

        // POST: Encomendas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,estado,email,morada,inicio,fim,custoTotal,detalhes,Fatura_referencia")] Encomenda encomenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(encomenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Fatura_referencia = new SelectList(db.Faturas, "referencia", "metodoPagamento", encomenda.Fatura_referencia);
            ViewBag.morada = new SelectList(db.Moradas, "id", "cidade", encomenda.morada);
            ViewBag.email = new SelectList(db.Utilizadors, "email", "password", encomenda.email);
            return View(encomenda);
        }

        // GET: Encomendas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encomenda encomenda = db.Encomendas.Find(id);
            if (encomenda == null)
            {
                return HttpNotFound();
            }
            return View(encomenda);
        }

        // POST: Encomendas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Encomenda encomenda = db.Encomendas.Find(id);
            db.Encomendas.Remove(encomenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Farma24/Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Farma24;

namespace Farma24.Controllers
{
    public class ProdutoesController : Controller
    {
        private Farma24DBEntities db = new Farma24DBEntities();

        // GET: Produtoes
        public ActionResult Index(String searchString)
        {
            var produtos = from m in db.Produtoes
                select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                produtos = produtos.Where(s => s.nome.Contains(searchString));
            }
            return View(produtos);
        }

        // GET: Produtoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produtoes/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produtoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codBarras,nome,categoria,preco,descricao,imagem")] Produto produto, HttpPostedFileBase file)
        {

            if (file != null)
            {
               
                string pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(
                                       Server.MapPath("~/Content/Images/medicamentos"), pic);
                produto.imagem = "~/Content/Images/medicamentos/" + pic;
                file.SaveAs(path);
            }
            else
            {
                produto.imagem = "~/Content/Images/pills.jpg";
            }

                if (ModelState.IsValid)
            {
                db.Produtoes.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produto);
        }

        // GET: Produtoes/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codBarras,nome,categoria,preco,descricao,imagem")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtoes.Find(id);
            db.Produtoes.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Farma24/Controllers/UtilizadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Farma24.Helper;
using Farma24.Models;

namespace Farma24.Controllers
{
    public class UtilizadorsController : Controller
    {
        private Farma24DBEntities db = new Farma24DBEntities();
        [Authorize(Roles = "admin")]
        // GET: Utilizadors
        public ActionResult Index()
        {
            return View(db.Utilizadors.ToList());
        }
        
        [Authorize(Roles = "admin,staff,user")]
        // GET: Utilizadors/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            //if(AuthorizedUser(id))
            //{
            id = UtilizadorHelper.FromBase64(id);
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
            //}
            /*else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }

        // GET: Utilizadors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utilizadors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "email,password,nome,iban,contacto,role")] Utilizador utilizador)
        {
            utilizador.SetUser();
            if (ModelState.IsValid)
            {
                db.Utilizadors.Add(utilizador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index","Produtoes");
        }

        // GET: Utilizadors/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            id = UtilizadorHelper.FromBase64(id);
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "email,password,nome,iban,contacto,role")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utilizador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(utilizador);
        }

        // GET: Utilizadors/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            id = UtilizadorHelper.FromBase64(id);
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {

            id = UtilizadorHelper.FromBase64(id);
            Utilizador utilizador = db.Utilizadors.Find(id);
            db.Utilizadors.Remove(utilizador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetUsernameCookie()
        {
            HttpCookie authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            FormsAuthenticationTicket t = FormsAuthentication.Decrypt(authCookie.Value);
            return t.Name;
        }


        public Utilizador GetUser()
        {
          return   db.Utilizadors.Find(GetUsernameCookie());
        }
        public bool AuthorizedUser(string id)
        {

            Utilizador cookieUtilizador = GetUser();

            return cookieUtilizador.role == "admin" || id == cookieUtilizador.email;
        }
    }
}

Farma24/Views/Shared/_Layout.cshtml
@using  Farma24.Helper

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>@ViewBag.Title - Farma24</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-header pull-right">
                    <form asp-controller="Produoes" asp-action="Index">
                        <p>
                            <input type="text" class="form-control" name="SearchString">
                        </p>
                    </form>
                </div>
                <a href='@Url.Action("Index", "Produtoes")'>
                    <img src='@Url.Content("~/Content/Images/logo.png")' height="50" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("Sobre nós", "About", "Home")</li>
                    <li>@Html.ActionLink("Contactos", "Contact", "Home")</li>
                </ul>
                @if (!Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Index", "Login")</li>
                        <li>@Html.ActionLink("Registar", "Index", "RegisterView")</li>
                    </ul>
                }
                else if (this.User.IsInRole("user"))
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Carrinho", "Index", "EncomendaProdutoView")</li>
                        <li>@Html.ActionLink("Historico", "Index", "Encomendas")</li>
                        <li>@Html.ActionLink("Perfil", "Details", "Utilizadors", new { id = UtilizadorHelper.ToBase64(User.Identity.Name) }, null)</li>
                        <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                    </ul>
                }
                else if (this.User.IsInRole("staff"))
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Entregas", "Create", "Funcionario")</li>
                        <li>@Html.ActionLink("Perfil", "Details", "Utilizadors", new { id = UtilizadorHelper.ToBase64(User.Identity.Name) }, null)</li>
                        <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                    </ul>
                }
                else if (this.User.IsInRole("admin"))
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Menu de Administrador","Index","Utilizadors")</li>
                        <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Perfil", "Details", "Utilizadors", new { id = UtilizadorHelper.ToBase64(User.Identity.Name) }, null)</li>
                        <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                    </ul>

                }
            </div>
        </div>
</nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Farma24</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>