Farma24/Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Farma24;

namespace Farma24.Controllers
{
    public class ProdutoesController : Controller
    {
        private Farma24DBEntities db = new Farma24DBEntities();

        // GET: Produtoes
        public ActionResult Index(String searchString)
        {
            var produtos = from m in db.Produtoes
                select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                produtos = produtos.Where(s => s.nome.Contains(searchString));
            }
            return View(produtos);
        }

        // GET: Produtoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produtoes/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produtoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codBarras,nome,categoria,preco,descricao,imagem")] Produto produto, HttpPostedFileBase file)
        {

            if (file != null)
            {
               
                string pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(
                                       Server.MapPath("~/Content/Images/medicamentos"), pic);
                produto.imagem = "~/Content/Images/medicamentos/" + pic;
                file.SaveAs(path);
            }
            else
            {
                produto.imagem = "~/Content/Images/pills.jpg";
            }

                if (ModelState.IsValid)
            {
                db.Produtoes.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produto);
        }

        // GET: Produtoes/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codBarras,nome,categoria,preco,descricao,imagem")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtoes.Find(id);
            db.Produtoes.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Farma24/Views/Produtoes/Create.cshtml
@model Farma24.Produto

@{
    ViewBag.Title = "Create";
    List<SelectListItem> categorias = new List<SelectListItem>();
    categorias.Add(new SelectListItem { Text = "Analgésico", Value = "Analgésico" });
    categorias.Add(new SelectListItem { Text = "Anti-histamínico", Value = "Anti-histamínico" });
    categorias.Add(new SelectListItem { Text = "Antibiótico", Value = "Antibiótico" });
    categorias.Add(new SelectListItem { Text = "Calmante", Value = "Calmante" });
    categorias.Add(new SelectListItem { Text = "Hormonal", Value = "Hormonal" });
    categorias.Add(new SelectListItem { Text = "Vitamínico", Value = "Vitamínico" });
    categorias.Add(new SelectListItem { Text = "Outro", Value = "Outro" });

}

<h1><span style="color: #297a6d; border: solid;"><b>NOVO PRODUTO</b></span></h1>

<div class="container">
    @using (Html.BeginForm("Create", "Produtoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.codBarras, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.codBarras, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.codBarras, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.categoria, categorias, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.preco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.preco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.preco, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="file" name="upload" class="upload" title="Choose a file to upload">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div class="btn btn-default back">
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

<style>
    input.upload {
        outline: none;
        cursor: pointer;
        font-size: 20px !important;
    }

    .back {
        background-color: #297a6d;
    }

    .back a {
        text-decoration: none;
        color: #ffffff
    }

        .back:hover {
            background-color: #39dd90;
            color: #ffffff
        }
</style>

Farma24/Views/Produtoes/Delete.cshtml
@model Farma24.Produto

@{
    ViewBag.Title = "Delete";
}

<h1><span style="color: #297a6d; border: solid;"><b>APAGAR</b></span></h1>

<h3>Tens a certeza que queres apagar este produto ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Categoria:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            Preço:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco)
        </dd>

        <dt>
            Descrição:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            Imagem:
        </dt>

        <dd>
            <img src='@Url.Content(Model.imagem)' style="height:200px; max-width: 100%" />
        </dd>

    </dl>
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div>
                <input type="submit" value="Delete" class="btn btn-default back" />
            </div>
            <div>
                <div class="btn btn-default back">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        }
    </div>
</div>


<style>
    .back {
        background-color: #297a6d;
        width: 100px;
        text-decoration: none;
        color: #ffffff
    }

        .back a {
            text-decoration: none;
            color: #ffffff
        }

        .back:hover {
            background-color: #39dd90;
            color: #ffffff
        }
</style>

Farma24/Views/Produtoes/Details.cshtml
@model Farma24.Produto

@{
    ViewBag.Title = "Details";
}

<h1>
    <span style="color: #297a6d; border: solid;">
        <b>
            @Html.DisplayFor(model => model.nome)
        </b>
    </span>
</h1>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Categoria:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            Preço:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco)€
        </dd>

        <dt>
            Descrição:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            Imagem:
        </dt>

        <dd>
            <img src='@Url.Content(Model.imagem)' style="height:200px; max-width: 100%" />
        </dd>

    </dl>
</div>


<p>
    @if (this.User.IsInRole("admin"))
    {
        <div class="btn btn-default back">
            @Html.ActionLink("Edit", "Edit", new { id = Model.codBarras })
        </div>
        <div class="btn btn-default back">
            @Html.ActionLink("Delete", "Delete", new { id = Model.codBarras })
        </div>
    }
   
    <div class="btn btn-default back">
        @Html.ActionLink("Back to List", "Index")
    </div>
</p>

<style>
    .back {
        background-color: #297a6d;
    }

        .back a {
            text-decoration: none;
            color: #ffffff
        }

        .back:hover {
            background-color: #39dd90;
            color: #ffffff
        }
</style>

Farma24/Views/Produtoes/Edit.cshtml
@model Farma24.Produto

@{
    ViewBag.Title = "Edit";
    List<SelectListItem> categorias = new List<SelectListItem>();
    categorias.Add(new SelectListItem { Text = "Analgésico", Value = "Analgésico" });
    categorias.Add(new SelectListItem { Text = "Anti-histamínico", Value = "Anti-histamínico" });
    categorias.Add(new SelectListItem { Text = "Antibiótico", Value = "Antibiótico" });
    categorias.Add(new SelectListItem { Text = "Calmante", Value = "Calmante" });
    categorias.Add(new SelectListItem { Text = "Hormonal", Value = "Hormonal" });
    categorias.Add(new SelectListItem { Text = "Vitamínico", Value = "Vitamínico" });
    categorias.Add(new SelectListItem { Text = "Outro", Value = "Outro" });
}

<h1>
    <span style="color: #297a6d; border: solid;">
        <b>
            Editar
        </b>
    </span>
</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.codBarras)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoria, categorias, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default back" />
            </div>
        </div>
    </div>
}

<div class="btn btn-default back">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    .back {
        background-color: #297a6d;
        text-decoration: none;
        color: #ffffff
    }

        .back a {
            text-decoration: none;
            color: #ffffff
        }

        .back:hover {
            background-color: #39dd90;
            color: #ffffff
        }
</style>

Farma24/Views/Produtoes/Index.cshtml
@using Farma24.Models
@model IEnumerable<Farma24.Produto>

@{
    ViewBag.Title = "Index";
}

<h1 style="text-align: center"><span style="color: #297a6d; border: solid;"><b>CATÁLOGO</b></span></h1>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            if(this.User.IsInRole("user"))
            {
                <text>
                <a href='@Url.Action("Create", "EncomendaProdutoView", new { id = item.codBarras })'>
                </text>
            }
            else{
                <text>
                <a href='@Url.Action("Details", "Produtoes", new { id = item.codBarras })'>
                </text>
            }
                <div class="col-lg-4 col-sm-6 portfolio-item container texto" style="margin: 30px 0px">
                    <div class="card h-100" style="display: block; margin: 0 auto;">
                        <img class="card-img-top" src='@Url.Content(item.imagem)' style="height:200px; display: block; margin: 0 auto; max-width: 100%" />
                        <div class="card-body" style="padding: 2px 16px">
                            <h4 class="card-title text-center bold" style="color: #297a6d;">
                                <b>@Html.DisplayFor(modelItem => item.nome)</b>
                            </h4>
                            <div class="card-text">
                                <p><b>Categoria: </b>@Html.DisplayFor(modelItem => item.categoria)</p>
                                <p><b>Preço: </b>@Html.DisplayFor(modelItem => item.preco)€</p>
                                <p class="hideContent"><b>Descrição: </b>@Html.DisplayFor(modelItem => item.descricao)</p>
                            </div>
                        </div>
                    </div>
                </div>
                @Html.Raw("</a>");
        }
    </div>
    @if (this.User.IsInRole("admin"))
    {
        <a href='@Url.Action("Create", "Produtoes")' class="button">
            Novo Produto
        </a>
    }
</div>